//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venteTest.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venteTest.Resources.Models.StringsAdmin", typeof(StringsAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acheteur.
        /// </summary>
        public static string Acheteur {
            get {
                return ResourceManager.GetString("Acheteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année.
        /// </summary>
        public static string Annee {
            get {
                return ResourceManager.GetString("Annee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année de départ.
        /// </summary>
        public static string AnneeDepart {
            get {
                return ResourceManager.GetString("AnneeDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année de fin.
        /// </summary>
        public static string AnneeFin {
            get {
                return ResourceManager.GetString("AnneeFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string Categorie {
            get {
                return ResourceManager.GetString("Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilité.
        /// </summary>
        public static string Civilite {
            get {
                return ResourceManager.GetString("Civilite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string Courriel {
            get {
                return ResourceManager.GetString("Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel confirmé.
        /// </summary>
        public static string CourrielConfirme {
            get {
                return ResourceManager.GetString("CourrielConfirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel du membre.
        /// </summary>
        public static string CourrielMembre {
            get {
                return ResourceManager.GetString("CourrielMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;inscription.
        /// </summary>
        public static string DateInscription {
            get {
                return ResourceManager.GetString("DateInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facteur de commission.
        /// </summary>
        public static string FacteurComm {
            get {
                return ResourceManager.GetString("FacteurComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Mise.
        /// </summary>
        public static string IdMise {
            get {
                return ResourceManager.GetString("IdMise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string Langue {
            get {
                return ResourceManager.GetString("Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de la mise.
        /// </summary>
        public static string MisePas {
            get {
                return ResourceManager.GetString("MisePas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mois de départ.
        /// </summary>
        public static string MoisDepart {
            get {
                return ResourceManager.GetString("MoisDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mois de fin.
        /// </summary>
        public static string MoisFin {
            get {
                return ResourceManager.GetString("MoisFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de départ.
        /// </summary>
        public static string ObjetDateDepart {
            get {
                return ResourceManager.GetString("ObjetDateDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        public static string ObjetDateFin {
            get {
                return ResourceManager.GetString("ObjetDateFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ObjetDescription {
            get {
                return ResourceManager.GetString("ObjetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée depuis le début de la vente.
        /// </summary>
        public static string ObjetDuree {
            get {
                return ResourceManager.GetString("ObjetDuree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ObjetImage {
            get {
                return ResourceManager.GetString("ObjetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le chemin de votre image est trop long car il dépasse 1024 caractères. Réessayer!.
        /// </summary>
        public static string ObjetImageErreur {
            get {
                return ResourceManager.GetString("ObjetImageErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise de départ.
        /// </summary>
        public static string ObjetMiseDepart {
            get {
                return ResourceManager.GetString("ObjetMiseDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string ObjetNom {
            get {
                return ResourceManager.GetString("ObjetNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone confirmé.
        /// </summary>
        public static string TelephoneConfirme {
            get {
                return ResourceManager.GetString("TelephoneConfirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendeur.
        /// </summary>
        public static string Vendeur {
            get {
                return ResourceManager.GetString("Vendeur", resourceCulture);
            }
        }
    }
}
