//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venteTest.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsRapports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsRapports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venteTest.Resources.Models.StringsRapports", typeof(StringsRapports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport no 1.
        /// </summary>
        public static string Rapport1 {
            get {
                return ResourceManager.GetString("Rapport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport no 2.
        /// </summary>
        public static string Rapport2 {
            get {
                return ResourceManager.GetString("Rapport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport no 3.
        /// </summary>
        public static string Rapport3 {
            get {
                return ResourceManager.GetString("Rapport3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport no 4.
        /// </summary>
        public static string Rapport4 {
            get {
                return ResourceManager.GetString("Rapport4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport no 5.
        /// </summary>
        public static string Rapport5 {
            get {
                return ResourceManager.GetString("Rapport5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voici votre rapport annuel des ventes réalisées et des commissions perçues pour la période de.
        /// </summary>
        public static string RapportAnnuelDescription {
            get {
                return ResourceManager.GetString("RapportAnnuelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voici votre rapport annuel des ventes réalisées et des commissions perçues pour l&apos;annéee.
        /// </summary>
        public static string RapportCommissionsDescriprtion {
            get {
                return ResourceManager.GetString("RapportCommissionsDescriprtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthèse des cotes de membres pour période de.
        /// </summary>
        public static string RapportCotesDescription {
            get {
                return ResourceManager.GetString("RapportCotesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport numéro.
        /// </summary>
        public static string RapportNo {
            get {
                return ResourceManager.GetString("RapportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthèse des ventes réalisées et des commissions année.
        /// </summary>
        public static string RapportVentesDescription {
            get {
                return ResourceManager.GetString("RapportVentesDescription", resourceCulture);
            }
        }
    }
}
