//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venteTest.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsManage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsManage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venteTest.Resources.Models.StringsManage", typeof(StringsManage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de vérification.
        /// </summary>
        public static string CodeVerif {
            get {
                return ResourceManager.GetString("CodeVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cote.
        /// </summary>
        public static string Cote {
            get {
                return ResourceManager.GetString("Cote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre d&apos;évaluations.
        /// </summary>
        public static string NbEvaluation {
            get {
                return ResourceManager.GetString("NbEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe actuel.
        /// </summary>
        public static string UsagerActuelP {
            get {
                return ResourceManager.GetString("UsagerActuelP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string UsagerAdresse {
            get {
                return ResourceManager.GetString("UsagerAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilité.
        /// </summary>
        public static string UsagerCivilite {
            get {
                return ResourceManager.GetString("UsagerCivilite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer le nouveau mot de passe.
        /// </summary>
        public static string UsagerConfirmerP {
            get {
                return ResourceManager.GetString("UsagerConfirmerP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string UsagerCourriel {
            get {
                return ResourceManager.GetString("UsagerCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string UsagerLangue {
            get {
                return ResourceManager.GetString("UsagerLangue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string UsagerNom {
            get {
                return ResourceManager.GetString("UsagerNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau mot de passe.
        /// </summary>
        public static string UsagerPassword {
            get {
                return ResourceManager.GetString("UsagerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string UsagerPrenom {
            get {
                return ResourceManager.GetString("UsagerPrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string UsagerTelephone {
            get {
                return ResourceManager.GetString("UsagerTelephone", resourceCulture);
            }
        }
    }
}
