//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venteTest.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsObjets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsObjets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venteTest.Resources.Models.StringsObjets", typeof(StringsObjets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission au vendeur.
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;ajout.
        /// </summary>
        public static string DateAjout {
            get {
                return ResourceManager.GetString("DateAjout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps depuis le début.
        /// </summary>
        public static string Duree {
            get {
                return ResourceManager.GetString("Duree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ObjetDescription {
            get {
                return ResourceManager.GetString("ObjetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ObjetImage {
            get {
                return ResourceManager.GetString("ObjetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de départ.
        /// </summary>
        public static string ObjetMiseDateDepart {
            get {
                return ResourceManager.GetString("ObjetMiseDateDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        public static string ObjetMiseDateFin {
            get {
                return ResourceManager.GetString("ObjetMiseDateFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string ObjetNom {
            get {
                return ResourceManager.GetString("ObjetNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string ObjetPrix {
            get {
                return ResourceManager.GetString("ObjetPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix vendu.
        /// </summary>
        public static string PrixVendu {
            get {
                return ResourceManager.GetString("PrixVendu", resourceCulture);
            }
        }
    }
}
