//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venteTest.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venteTest.Resources.Views.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos.
        /// </summary>
        public static string APropos {
            get {
                return ResourceManager.GetString("APropos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour:.
        /// </summary>
        public static string Bonjour {
            get {
                return ResourceManager.GetString("Bonjour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer vos paramètres de compte.
        /// </summary>
        public static string ChangerParametres {
            get {
                return ResourceManager.GetString("ChangerParametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactez-nous.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyez ma demande.
        /// </summary>
        public static string ContactBoutonEnvoyer {
            get {
                return ResourceManager.GetString("ContactBoutonEnvoyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vider les champs.
        /// </summary>
        public static string ContactBoutonVider {
            get {
                return ResourceManager.GetString("ContactBoutonVider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel:.
        /// </summary>
        public static string ContactCourriel {
            get {
                return ResourceManager.GetString("ContactCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez utiliser le formulaire ci-dessous pour nous contacter..
        /// </summary>
        public static string ContactHeader {
            get {
                return ResourceManager.GetString("ContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message:.
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez vous nous prouver que vous êtes humain: .
        /// </summary>
        public static string ContactReCaptcha {
            get {
                return ResourceManager.GetString("ContactReCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string Courriel {
            get {
                return ResourceManager.GetString("Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string CreerCategorie {
            get {
                return ResourceManager.GetString("CreerCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;ajout.
        /// </summary>
        public static string CreerDateAjout {
            get {
                return ResourceManager.GetString("CreerDateAjout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CreerDescription {
            get {
                return ResourceManager.GetString("CreerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée de mise en vente.
        /// </summary>
        public static string CreerDuree {
            get {
                return ResourceManager.GetString("CreerDuree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string CreerImage {
            get {
                return ResourceManager.GetString("CreerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string CreerNom {
            get {
                return ResourceManager.GetString("CreerNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreerNouveau {
            get {
                return ResourceManager.GetString("CreerNouveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string CreerPrix {
            get {
                return ResourceManager.GetString("CreerPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnecter.
        /// </summary>
        public static string Deconnexion {
            get {
                return ResourceManager.GetString("Deconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors du traitement de votre demande..
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode développeur.
        /// </summary>
        public static string ErrorDev1 {
            get {
                return ResourceManager.GetString("ErrorDev1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;échange vers l&apos;environnement de développement affichera des informations plus détaillées sur l&apos;erreur qui s&apos;est produite..
        /// </summary>
        public static string ErrorDev2 {
            get {
                return ResourceManager.GetString("ErrorDev2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;environnement de développement ne doit pas être activé dans les applications déployées, car il peut générer des informations sensibles à partir d&apos;exceptions affichées aux utilisateurs finaux. Pour le débogage local, l&apos;environnement de développement peut être activé en définissant la variable d&apos;environnement ASPNETCORE_ENVIRONMENT sur Développement et en redémarrant l&apos;application..
        /// </summary>
        public static string ErrorDev3 {
            get {
                return ResourceManager.GetString("ErrorDev3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de la requête: .
        /// </summary>
        public static string ErrorRequete {
            get {
                return ResourceManager.GetString("ErrorRequete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string ErrorTitre {
            get {
                return ResourceManager.GetString("ErrorTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorsque vous joignez notre site d&apos;encans, vous convenez avoir compris les modalités suivantes:.
        /// </summary>
        public static string FAQDescriptif {
            get {
                return ResourceManager.GetString("FAQDescriptif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrer les objets par nom: .
        /// </summary>
        public static string FiltrerObjetsNom {
            get {
                return ResourceManager.GetString("FiltrerObjetsNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string GererCompte {
            get {
                return ResourceManager.GetString("GererCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message a été envoyé..
        /// </summary>
        public static string MessageEnvoye {
            get {
                return ResourceManager.GetString("MessageEnvoye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message a été envoyé..
        /// </summary>
        public static string MessageEnvoyeLong {
            get {
                return ResourceManager.GetString("MessageEnvoyeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miser!.
        /// </summary>
        public static string Miser {
            get {
                return ResourceManager.GetString("Miser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon histoire.
        /// </summary>
        public static string MonHistoire {
            get {
                return ResourceManager.GetString("MonHistoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string NomUtilisateur {
            get {
                return ResourceManager.GetString("NomUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes objets a acheter.
        /// </summary>
        public static string ObjetAcheter {
            get {
                return ResourceManager.GetString("ObjetAcheter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un objet.
        /// </summary>
        public static string ObjetAjouter {
            get {
                return ResourceManager.GetString("ObjetAjouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes objets a vendre.
        /// </summary>
        public static string ObjetVendre {
            get {
                return ResourceManager.GetString("ObjetVendre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou.
        /// </summary>
        public static string Ou {
            get {
                return ResourceManager.GetString("Ou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Précédent.
        /// </summary>
        public static string Precedent {
            get {
                return ResourceManager.GetString("Precedent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des questions couramment demandées:.
        /// </summary>
        public static string QuestionsCourantes {
            get {
                return ResourceManager.GetString("QuestionsCourantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher !.
        /// </summary>
        public static string Rechercher {
            get {
                return ResourceManager.GetString("Rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string SeConnecter {
            get {
                return ResourceManager.GetString("SeConnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string SInscrire {
            get {
                return ResourceManager.GetString("SInscrire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string Suivant {
            get {
                return ResourceManager.GetString("Suivant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la liste complète des objets.
        /// </summary>
        public static string ToutAfficherObjets {
            get {
                return ResourceManager.GetString("ToutAfficherObjets", resourceCulture);
            }
        }
    }
}
