//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venteTest.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venteTest.Resources.Views.StringsHome", typeof(StringsHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyez-nous vos commentaires..
        /// </summary>
        public static string ContactDescription {
            get {
                return ResourceManager.GetString("ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les paiements sont effectués entre les parties, lorsqu&apos;elles se rencontrent..
        /// </summary>
        public static string FAQ1 {
            get {
                return ResourceManager.GetString("FAQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a un frais de commission sur chaque transaction qui est complétée..
        /// </summary>
        public static string FAQ2 {
            get {
                return ResourceManager.GetString("FAQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les acheteurs et vendeurs évaluent chacun la transaction qui a été complétée..
        /// </summary>
        public static string FAQ3 {
            get {
                return ResourceManager.GetString("FAQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si la réputation d&apos;un usager atteint la note de -6, un message est envoyé à l&apos;usager fautif..
        /// </summary>
        public static string FAQ4 {
            get {
                return ResourceManager.GetString("FAQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advenant que la réputation d&apos;un usager atteigne -9, le compte de cet usager sera effacé..
        /// </summary>
        public static string FAQ5 {
            get {
                return ResourceManager.GetString("FAQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si vous avez des questions, vous pouvez nous contacter via le formulaire situé à la page.
        /// </summary>
        public static string FAQ6 {
            get {
                return ResourceManager.GetString("FAQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorsque vous joignez notre site d&apos;encans, vous convenez avoir compris les modalités suivantes:.
        /// </summary>
        public static string FAQDescription {
            get {
                return ResourceManager.GetString("FAQDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string IndexCategorie {
            get {
                return ResourceManager.GetString("IndexCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;inscription.
        /// </summary>
        public static string IndexDateInscription {
            get {
                return ResourceManager.GetString("IndexDateInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer ici pour filtrer le champs!.
        /// </summary>
        public static string IndexFiltrerChamps {
            get {
                return ResourceManager.GetString("IndexFiltrerChamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrer les objets par:.
        /// </summary>
        public static string IndexFiltrerPar {
            get {
                return ResourceManager.GetString("IndexFiltrerPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        public static string IndexFin {
            get {
                return ResourceManager.GetString("IndexFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISER!.
        /// </summary>
        public static string IndexMise {
            get {
                return ResourceManager.GetString("IndexMise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise de départ.
        /// </summary>
        public static string IndexMiseDepart {
            get {
                return ResourceManager.GetString("IndexMiseDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise présentement en avance.
        /// </summary>
        public static string IndexMiseEnAvance {
            get {
                return ResourceManager.GetString("IndexMiseEnAvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique.
        /// </summary>
        public static string IndexMiseHistorique {
            get {
                return ResourceManager.GetString("IndexMiseHistorique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string IndexNom {
            get {
                return ResourceManager.GetString("IndexNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Précédent.
        /// </summary>
        public static string IndexPrecedent {
            get {
                return ResourceManager.GetString("IndexPrecedent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prochain.
        /// </summary>
        public static string IndexProchain {
            get {
                return ResourceManager.GetString("IndexProchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher!.
        /// </summary>
        public static string IndexRechercher {
            get {
                return ResourceManager.GetString("IndexRechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par: .
        /// </summary>
        public static string IndexRechercherPar {
            get {
                return ResourceManager.GetString("IndexRechercherPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner une catégorie....
        /// </summary>
        public static string IndexSelectCategorie {
            get {
                return ResourceManager.GetString("IndexSelectCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spécifications complètes.
        /// </summary>
        public static string IndexSpecs {
            get {
                return ResourceManager.GetString("IndexSpecs", resourceCulture);
            }
        }
    }
}
