//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venteTest.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsHome() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venteTest.Resources.Views.StringsHome", typeof(StringsHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluation.
        /// </summary>
        public static string AjouterEvaluation {
            get {
                return ResourceManager.GetString("AjouterEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos.
        /// </summary>
        public static string APropos {
            get {
                return ResourceManager.GetString("APropos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyez-nous vos commentaires..
        /// </summary>
        public static string ContactDescription {
            get {
                return ResourceManager.GetString("ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les paiements sont effectués entre les parties, lorsqu&apos;elles se rencontrent..
        /// </summary>
        public static string FAQ1 {
            get {
                return ResourceManager.GetString("FAQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a un frais de commission sur chaque transaction qui est complétée..
        /// </summary>
        public static string FAQ2 {
            get {
                return ResourceManager.GetString("FAQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les acheteurs et vendeurs évaluent chacun la transaction qui a été complétée..
        /// </summary>
        public static string FAQ3 {
            get {
                return ResourceManager.GetString("FAQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si la réputation d&apos;un usager atteint la note de -6, un message est envoyé à l&apos;usager fautif..
        /// </summary>
        public static string FAQ4 {
            get {
                return ResourceManager.GetString("FAQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advenant que la réputation d&apos;un usager atteigne -9, le compte de cet usager sera effacé..
        /// </summary>
        public static string FAQ5 {
            get {
                return ResourceManager.GetString("FAQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous avez des questions, vous pouvez nous contacter via le formulaire situé à la page.
        /// </summary>
        public static string FAQ6 {
            get {
                return ResourceManager.GetString("FAQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorsque vous joignez notre site d&apos;encans, vous convenez avoir compris les modalités suivantes:.
        /// </summary>
        public static string FAQDescription {
            get {
                return ResourceManager.GetString("FAQDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forums.
        /// </summary>
        public static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie.
        /// </summary>
        public static string IndexCategorie {
            get {
                return ResourceManager.GetString("IndexCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;inscription.
        /// </summary>
        public static string IndexDateInscription {
            get {
                return ResourceManager.GetString("IndexDateInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cliquer ici pour filtrer le champs!.
        /// </summary>
        public static string IndexFiltrerChamps {
            get {
                return ResourceManager.GetString("IndexFiltrerChamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtrer les objets par:.
        /// </summary>
        public static string IndexFiltrerPar {
            get {
                return ResourceManager.GetString("IndexFiltrerPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de fin.
        /// </summary>
        public static string IndexFin {
            get {
                return ResourceManager.GetString("IndexFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MISER!.
        /// </summary>
        public static string IndexMise {
            get {
                return ResourceManager.GetString("IndexMise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise de départ.
        /// </summary>
        public static string IndexMiseDepart {
            get {
                return ResourceManager.GetString("IndexMiseDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise présentement en avance.
        /// </summary>
        public static string IndexMiseEnAvance {
            get {
                return ResourceManager.GetString("IndexMiseEnAvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique.
        /// </summary>
        public static string IndexMiseHistorique {
            get {
                return ResourceManager.GetString("IndexMiseHistorique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string IndexNom {
            get {
                return ResourceManager.GetString("IndexNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Précédent.
        /// </summary>
        public static string IndexPrecedent {
            get {
                return ResourceManager.GetString("IndexPrecedent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prochain.
        /// </summary>
        public static string IndexProchain {
            get {
                return ResourceManager.GetString("IndexProchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher!.
        /// </summary>
        public static string IndexRechercher {
            get {
                return ResourceManager.GetString("IndexRechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Par: .
        /// </summary>
        public static string IndexRechercherPar {
            get {
                return ResourceManager.GetString("IndexRechercherPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner une catégorie....
        /// </summary>
        public static string IndexSelectCategorie {
            get {
                return ResourceManager.GetString("IndexSelectCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spécifications complètes.
        /// </summary>
        public static string IndexSpecs {
            get {
                return ResourceManager.GetString("IndexSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revues.
        /// </summary>
        public static string Revues {
            get {
                return ResourceManager.GetString("Revues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
    }
}
