//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venteTest.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsObjets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsObjets() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venteTest.Resources.Views.StringsObjets", typeof(StringsObjets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes achats.
        /// </summary>
        public static string AcheterTitre {
            get {
                return ResourceManager.GetString("AcheterTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retourner à l&apos;accueil.
        /// </summary>
        public static string BackToIndex {
            get {
                return ResourceManager.GetString("BackToIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retourner à la liste.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        public static string BoutonCreer {
            get {
                return ResourceManager.GetString("BoutonCreer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Télécharger !.
        /// </summary>
        public static string btnTelecharger {
            get {
                return ResourceManager.GetString("btnTelecharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder.
        /// </summary>
        public static string ButtonSauvegarder {
            get {
                return ResourceManager.GetString("ButtonSauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        public static string CreateCreer {
            get {
                return ResourceManager.GetString("CreateCreer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet.
        /// </summary>
        public static string CreateObjet {
            get {
                return ResourceManager.GetString("CreateObjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes vous sûr de vouloir effacer ceci?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string DeleteSupprimer {
            get {
                return ResourceManager.GetString("DeleteSupprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Éditer.
        /// </summary>
        public static string DetailsEditer {
            get {
                return ResourceManager.GetString("DetailsEditer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet.
        /// </summary>
        public static string EditObjet {
            get {
                return ResourceManager.GetString("EditObjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string EditTitre {
            get {
                return ResourceManager.GetString("EditTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une catégorie.
        /// </summary>
        public static string IndexCategorie {
            get {
                return ResourceManager.GetString("IndexCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie.
        /// </summary>
        public static string IndexCategorie1 {
            get {
                return ResourceManager.GetString("IndexCategorie1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un nouvel objet.
        /// </summary>
        public static string IndexCreer {
            get {
                return ResourceManager.GetString("IndexCreer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;inscription.
        /// </summary>
        public static string IndexDateInscription {
            get {
                return ResourceManager.GetString("IndexDateInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effacer.
        /// </summary>
        public static string IndexEffacer {
            get {
                return ResourceManager.GetString("IndexEffacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cliquer ici pour filtrer les champs!.
        /// </summary>
        public static string IndexFiltrerChamps {
            get {
                return ResourceManager.GetString("IndexFiltrerChamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de fin.
        /// </summary>
        public static string IndexFin {
            get {
                return ResourceManager.GetString("IndexFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher toute la liste.
        /// </summary>
        public static string IndexListe {
            get {
                return ResourceManager.GetString("IndexListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise en cours.
        /// </summary>
        public static string IndexMiseCourante {
            get {
                return ResourceManager.GetString("IndexMiseCourante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise de départ.
        /// </summary>
        public static string IndexMiseDepart {
            get {
                return ResourceManager.GetString("IndexMiseDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise présentement en avance.
        /// </summary>
        public static string IndexMiseEnAvance {
            get {
                return ResourceManager.GetString("IndexMiseEnAvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string IndexNom {
            get {
                return ResourceManager.GetString("IndexNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Précédent.
        /// </summary>
        public static string IndexPrecedent {
            get {
                return ResourceManager.GetString("IndexPrecedent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix.
        /// </summary>
        public static string IndexPrix {
            get {
                return ResourceManager.GetString("IndexPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prochain.
        /// </summary>
        public static string IndexProchain {
            get {
                return ResourceManager.GetString("IndexProchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher!.
        /// </summary>
        public static string IndexRechercher {
            get {
                return ResourceManager.GetString("IndexRechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes objets à vendre.
        /// </summary>
        public static string IndexTitre {
            get {
                return ResourceManager.GetString("IndexTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique de mes Enchères.
        /// </summary>
        public static string LayoutDescription {
            get {
                return ResourceManager.GetString("LayoutDescription", resourceCulture);
            }
        }
    }
}
