//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venteTest.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venteTest.Resources.Views.StringsAdmin", typeof(StringsAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher tous les items.
        /// </summary>
        public static string AfficherTous {
            get {
                return ResourceManager.GetString("AfficherTous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string ButtonCreer {
            get {
                return ResourceManager.GetString("ButtonCreer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string CreateCategorie {
            get {
                return ResourceManager.GetString("CreateCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes vous sûr de vouloir effacer ceci?.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De retour à la liste.
        /// </summary>
        public static string EditBackToList {
            get {
                return ResourceManager.GetString("EditBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string EditCategorie {
            get {
                return ResourceManager.GetString("EditCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string EditSave {
            get {
                return ResourceManager.GetString("EditSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier une catégorie.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De retour à la gestion des membres.
        /// </summary>
        public static string EmailBackToMemberManagement {
            get {
                return ResourceManager.GetString("EmailBackToMemberManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer les paramètres du courriel.
        /// </summary>
        public static string EmailParametres {
            get {
                return ResourceManager.GetString("EmailParametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string EmailSend {
            get {
                return ResourceManager.GetString("EmailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Écrire au membre.
        /// </summary>
        public static string EmailTitle {
            get {
                return ResourceManager.GetString("EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectioner un courriel.
        /// </summary>
        public static string HistoriqueCourriel {
            get {
                return ResourceManager.GetString("HistoriqueCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique par usager:.
        /// </summary>
        public static string HistoriqueUsager {
            get {
                return ResourceManager.GetString("HistoriqueUsager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une nouvelle catégorie.
        /// </summary>
        public static string IndexCreerNouvelle {
            get {
                return ResourceManager.GetString("IndexCreerNouvelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string IndexDelete {
            get {
                return ResourceManager.GetString("IndexDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éditer.
        /// </summary>
        public static string IndexEdit {
            get {
                return ResourceManager.GetString("IndexEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des catégories.
        /// </summary>
        public static string IndexGestionCategories {
            get {
                return ResourceManager.GetString("IndexGestionCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opérations de l&apos;administrateur.
        /// </summary>
        public static string LayoutDescription {
            get {
                return ResourceManager.GetString("LayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveaux membres (24 hrs).
        /// </summary>
        public static string Members24 {
            get {
                return ResourceManager.GetString("Members24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les membres.
        /// </summary>
        public static string MembersAll {
            get {
                return ResourceManager.GetString("MembersAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option d&apos;affichage des membres.
        /// </summary>
        public static string MembersDisplay {
            get {
                return ResourceManager.GetString("MembersDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membres.
        /// </summary>
        public static string Membres {
            get {
                return ResourceManager.GetString("Membres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string MembresAdresse {
            get {
                return ResourceManager.GetString("MembresAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilité.
        /// </summary>
        public static string MembresCivilite {
            get {
                return ResourceManager.GetString("MembresCivilite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string MembresCourriel {
            get {
                return ResourceManager.GetString("MembresCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel confirmé.
        /// </summary>
        public static string MembresCourrielConfirme {
            get {
                return ResourceManager.GetString("MembresCourrielConfirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;enrolement.
        /// </summary>
        public static string MembresDateEnrolement {
            get {
                return ResourceManager.GetString("MembresDateEnrolement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des membres.
        /// </summary>
        public static string MembresGestion {
            get {
                return ResourceManager.GetString("MembresGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string MembresLangue {
            get {
                return ResourceManager.GetString("MembresLangue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string MembresNom {
            get {
                return ResourceManager.GetString("MembresNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string MembresPrenom {
            get {
                return ResourceManager.GetString("MembresPrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation des membres.
        /// </summary>
        public static string MembresRating {
            get {
                return ResourceManager.GetString("MembresRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone.
        /// </summary>
        public static string MembresTelephone {
            get {
                return ResourceManager.GetString("MembresTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de départ.
        /// </summary>
        public static string MiseDateDepart {
            get {
                return ResourceManager.GetString("MiseDateDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        public static string MiseDateFin {
            get {
                return ResourceManager.GetString("MiseDateFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to État.
        /// </summary>
        public static string MiseEtat {
            get {
                return ResourceManager.GetString("MiseEtat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise initiale.
        /// </summary>
        public static string MiseInitiale {
            get {
                return ResourceManager.GetString("MiseInitiale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée.
        /// </summary>
        public static string MiseJours {
            get {
                return ResourceManager.GetString("MiseJours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration des mises.
        /// </summary>
        public static string NavBid {
            get {
                return ResourceManager.GetString("NavBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des catégories.
        /// </summary>
        public static string NavCategorie {
            get {
                return ResourceManager.GetString("NavCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des membres.
        /// </summary>
        public static string NavMembre {
            get {
                return ResourceManager.GetString("NavMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des objets.
        /// </summary>
        public static string NavObjets {
            get {
                return ResourceManager.GetString("NavObjets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string NavOptions {
            get {
                return ResourceManager.GetString("NavOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objets.
        /// </summary>
        public static string Objets {
            get {
                return ResourceManager.GetString("Objets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveaux items.
        /// </summary>
        public static string OptionNouveaux {
            get {
                return ResourceManager.GetString("OptionNouveaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options d&apos;affichage.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les items.
        /// </summary>
        public static string OptionsTous {
            get {
                return ResourceManager.GetString("OptionsTous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items vendus.
        /// </summary>
        public static string OptionVendus {
            get {
                return ResourceManager.GetString("OptionVendus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items en vente.
        /// </summary>
        public static string OptionVente {
            get {
                return ResourceManager.GetString("OptionVente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapports.
        /// </summary>
        public static string Rapports {
            get {
                return ResourceManager.GetString("Rapports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventes annuelles.
        /// </summary>
        public static string VentesAnnuelles {
            get {
                return ResourceManager.GetString("VentesAnnuelles", resourceCulture);
            }
        }
    }
}
