//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venteTest.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsMember {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsMember() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venteTest.Resources.Views.StringsMember", typeof(StringsMember).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membres actifs.
        /// </summary>
        public static string Actif {
            get {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cote d&apos;acheteur.
        /// </summary>
        public static string BuyerRating {
            get {
                return ResourceManager.GetString("BuyerRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation de l&apos;acheteur: Note moyenne attribuée par le vendeur à ses lauréats.
        /// </summary>
        public static string BuyerRatingEx {
            get {
                return ResourceManager.GetString("BuyerRatingEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les objets actifs.
        /// </summary>
        public static string DisplayActive {
            get {
                return ResourceManager.GetString("DisplayActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les évaluations vont de -3 à 3 dans l&apos;ordre croissant de l&apos;évaluation.
        /// </summary>
        public static string RatingsExplanation {
            get {
                return ResourceManager.GetString("RatingsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher....
        /// </summary>
        public static string Rechercher {
            get {
                return ResourceManager.GetString("Rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitailiser.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cote de vendeur.
        /// </summary>
        public static string SellerRating {
            get {
                return ResourceManager.GetString("SellerRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation du vendeur: Note moyenne reçue par le vendeur.
        /// </summary>
        public static string SellerRatingEx {
            get {
                return ResourceManager.GetString("SellerRatingEx", resourceCulture);
            }
        }
    }
}
